name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Testing on Node ${{matrix.node_version}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [10, 12, 13]
    steps:
      - name: Checkout Master
        uses: actions/checkout@v1
      - name: Use Node ${{matrix.node_version}}
        uses: actions/setup-node@master
        with:
          version: ${{ matrix.node_version }}
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
