name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Testing on Node ${{matrix.node_version}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [10, 12, 13]
    steps:
      - name: Checkout Master
        uses: actions/checkout@v1
      - name: Use Node ${{matrix.node_version}}
        uses: actions/setup-node@master
        with:
          version: ${{ matrix.node_version }}
      - name: Install Dependencies
        run: npm install
      - name: Lerna Bootstrap
        run: npm run lerna bootstrap
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
